### ISSUE TITLE
Fuel purchases

### ISSUE THREAD

**Issue by vivanov1410** [makkke/road-so-far#3]
- [ ] list fuel purchases
- [ ] create fuel purchase
- [ ] update fuel purchase
- [ ] remove fuel purchase
- [ ] attach receipt image to fuel purchase
