### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by vivanov1410** [makkke/road-so-far#4]
- [ ] total fuel purchases this month
- [ ] total kms traveled this month
- [ ] average litres per km
- ???
